# backend/Dockerfile
FROM python:3.12-slim

# Set working directory
WORKDIR /app

# Copy requirements first (for caching)
COPY requirement.txt .

# Install dependencies
RUN pip install --no-cache-dir -r requirement.txt
RUN pip install flask-cors requests

# Copy backend code
COPY . .

# Expose port
EXPOSE 5000

# Run the app
CMD ["python", "app.py"]
