apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-blue
  labels:
    app: weather-frontend
    version: blue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weather-frontend
      version: blue
  template:
    metadata:
      labels:
        app: weather-frontend
        version: blue
    spec:
      containers:
      - name: frontend
        image: rahul4475/weather-frontend:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "100m"
          limits:
            cpu: "500m"
