name: Weather Project CI/CD

on:
  push:
    branches:
      - main

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
  OPENWEATHER_API_KEY: ${{ secrets.OPENWEATHER_API_KEY }}

jobs:

  build-and-push:
    runs-on: ubuntu-latest

    steps:
    # ---------------- Checkout ----------------
    - name: Checkout repo
      uses: actions/checkout@v3

    # ---------------- Docker Buildx ----------------
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # ---------------- DockerHub Login ----------------
    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    # ---------------- Build & Push Frontend Blue ----------------
    - name: Build frontend-blue image
      run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/weather-frontend:blue ./frontend

    - name: Scan frontend-blue image with Trivy
      uses: aquasecurity/trivy-action@v2
      with:
        image-ref: ${{ secrets.DOCKERHUB_USERNAME }}/weather-frontend:blue
        severity: CRITICAL,HIGH
        exit-code: '1'  # fail workflow if vulnerabilities found

    - name: Push frontend-blue image
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/weather-frontend:blue

    # ---------------- Build & Push Frontend Green ----------------
    - name: Build frontend-green image
      run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/weather-frontend:green ./frontend

    - name: Scan frontend-green image with Trivy
      uses: aquasecurity/trivy-action@v2
      with:
        image-ref: ${{ secrets.DOCKERHUB_USERNAME }}/weather-frontend:green
        severity: CRITICAL,HIGH
        exit-code: '1'

    - name: Push frontend-green image
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/weather-frontend:green

    # ---------------- Build & Push Backend ----------------
    - name: Build backend image
      run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/weather-backend:latest ./backend

    - name: Scan backend image with Trivy
      uses: aquasecurity/trivy-action@v2
      with:
        image-ref: ${{ secrets.DOCKERHUB_USERNAME }}/weather-backend:latest
        severity: CRITICAL,HIGH
        exit-code: '1'

    - name: Push backend image
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/weather-backend:latest
